version: '3.8'

services:

  mariadb:
    build: ./mariadb
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - network
    ports:
      - "3306:3306"

  wordpress:
    build: ./wordpress
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    restart: unless-stopped
    volumes:
      - wp-data:/var/www/html/
    env_file:
      - .env
    networks:
      - network

  nginx:
    build: ./nginx
    image: nginx
    container_name: nginx
    depends_on:
      - wordpress
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - wp-data:/var/www/html/
    networks:
      - network
    ports:
      - "443:443"

networks:
  network:
    driver: bridge

volumes:
  wp-data:
    driver_opts:
      type: none
      o: bind #Bind Mount the host directory /home/$USER/data/wordpress to the volume wp-data.
      device: /home/$USER/data/wordpress #uses it as a volume on the host machine
      
  db-data:
    driver_opts:
      type: none
      o: bind
      device: /home/$USER/data/mariadb